var express = require('express');
var app = express();
var fs = require('fs');
const bodyParser = require('body-parser');
const multer = require('multer');
const uuidv4 = require('uuid/v4');
const path = require('path');
//var upload = multer({ dest: 'uploads/' });
// configure storage
var storage = multer.diskStorage({
    destination: function(req, file, cb) {
        cb(null, './uploads');
     },
    filename: function (req, file, cb) {
        cb(null , file.originalname);
    }
});

app.get('/:name', function (req, res) {
    console.log("download ",req.params.name);
    res.sendFile('images/'+req.params.name , { root : __dirname});
    //res.sendFile('images/test.txt' , { root : __dirname});
});

var upload = multer({ storage: storage })

    app.post('/upload',upload.single('fileData'), (req, res,next) => {
    //  logger.info(req.file);//this will be automatically set by multer
      //logger.info(req.body);
      //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
      //
      //
      //     console.log("The file was saved!");
      // });
      // fs.readFile(req.file.path,(err, contents)=> {
      //      if (err) {
      //      console.log('Error: ', err);
      //     }else{
      //      console.log('File contents ',contents);
      //     }
      // });
      // req.send("rec");
          try {
        res.send(req.file);
      }catch(err) {
        res.send(400);
      }
    });




// Change the 404 message modifing the middleware
app.use(function(req, res, next) {
    res.status(404).send("Sorry, that route doesn't exist. Have a nice day :)");
});

// start the server in the port 3000 !
app.listen(5000, function () {
    console.log('Example app listening on port 5000.');
});
